### ISSUE TITLE
Do not suggest snippets in comments

### ISSUE THREAD

**Issue by joshsedl** [andy-blum/drupal-smart-snippets#12]
Quite often when writing all kinds of comments (`/**/`, `/***/`, `//`) the suggestions are added because a word matches partially.

When pressing enter then, the snippet is added.
This is very helpful in code, but not in comments, so it would be great, if comments could be excluded generally.

Thank you for this great plugin and happy Drupaling :)

**Comment by andy-blum** [comment]
Hey, @joshsedl, thanks for the feedback. Unfortunately, I'm not sure of a way to control when snippets are appropriate in VS code. This does not appear to be a part of the [VS Code snippet syntax](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax)

**Comment by joshsedl** [comment]
Unfortunate! But thank you for taking the time, to evaluate my issue! 👍
