### ISSUE TITLE
Add @param and @return to docbloc

### ISSUE THREAD

**Issue by lostcarpark** [andy-blum/drupal-smart-snippets#15]
At present, the docbloc Smart Snippits generates is fairly minimal, e.g.:

```
/**
 * Implements hook_form_alter().
 */
```
It would be great if a more complete docbloc could be generated. For example:
```
/**
 * Implements hook_form_alter().
 * 
 * @param array &$form
 *   The form array.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The current state of the form.
 * @param string $form_id
 *   The form identification.
 */
```

**Comment by andy-blum** [comment]
This is currently not in line with [the Drupal coding standards](https://www.drupal.org/docs/develop/standards/php/api-documentation-and-comment-standards#hookimpl), though there is [an open issue](https://www.drupal.org/project/coding_standards/issues/3056368) to change this

**Comment by lostcarpark** [comment]
Thanks for the clarification.
