### ISSUE TITLE
No intellisense for the services

### ISSUE THREAD

**Issue by mauicode26** [andy-blum/drupal-smart-snippets#26]
I've found that there is no intellisense when doing something like:

`$current_user_service = \Drupal::currentUser();`

I am on an M1 Mac, and have verified this is the case for both D9 and D10.

**Comment by andy-blum** [comment]
This feature requires the use of another extension like [PHP Intelephense](https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client).

The snippet provides the service's return type:

```php
/**
 * @var Drupal\Core\Session\AccountProxy
 */
$current_user_service = \Drupal::service('current_user');
```

And intelephense uses the type to provide the properties/methods

**Comment by mauicode26** [comment]
Ahh!  My apologies.  It works once PHP Intelephense is installed/enabled.  Thanks.
