### ISSUE TITLE
Add support for entity_autocomplete form element in autocomplete 

### ISSUE THREAD

**Issue by ultimike** [andy-blum/drupal-smart-snippets#27]
When using `@FormElement` to autocomplete form elements, the `entity_autocomplete` element is missing. 

The scraper needs to add `/core/lib/Drupal/Core/Entity/Element/` to include it.

thanks,
-mike

**Comment by andy-blum** [comment]
Seems [our scraper](https://github.com/andy-blum/drupal-smart-snippets/blob/main/src/getElementFiles.js#L5-L8) is not scanning the directory where the [entity_autocomplete element](https://git.drupalcode.org/project/drupal/-/blob/11.x/core/lib/Drupal/Core/Entity/Element/EntityAutocomplete.php?ref_type=heads) is defined:

```js
export async function getElementFiles(version) {
	return new Promise((res) => {
		find.file(`tmp/drupal-${version}/core/lib/Drupal/Core/Render/Element/`, (file) => {
			const filtered = file.filter((filename) => filename.endsWith('.php'));
			res(filtered);
		});
	});
}
```

Might be worth scanning `/core/lib/Drupal/Core/*/Element/`

**Comment by ultimike** [comment]
Nudge (pretty please.)

**Comment by andy-blum** [comment]
So _impatient_

**Comment by ultimike** [comment]
Heh - indeed.

I have no idea if the pull request will work (no idea if wildcards are allowed.) In fact, I did it during a module development class I was teaching. 🤞🏼

thanks,
-mike

**Comment by andy-blum** [comment]
I'll take a look - updating to include 10.3 and 11.0 first

**Comment by ultimike** [comment]
I see that this was added to the 2.2 release, but for whatever reason, it suggests incorrect code ☹️

The main issue is that the `#type` should be `entity_autocomplete`, but Drupal Smart Snippets is showing and providing `entityautocomplete` (no underscore.)

<img width="626" alt="Screenshot 2024-10-22 at 12 15 43 PM" src="https://github.com/user-attachments/assets/23ba012d-99af-4b80-af6a-264a661975c1">

Here's the code snippet (completion) it provides:

```
      '#type' => 'entityautocomplete',
      '#title' => t(''),
      '#title_display' => 'before',
      '#description' => t(''),
      '#required' => TRUE,
      '#target_type' => '',
      '#tags' => '',
      '#default_value' => '',
      '#selection_handler' => '',
      '#selection_settings' => '',
      '#autocreate' => '',
      '#process_default_value' => '',
      '#validate_reference' => '',
```

In fact, I think this is an issue for all Form elements (maybe render elements as well) that have underscores in their `#type` values. For example, Drupal Smart Snippets also outputs `'#type' => 'contextuallinksplaceholder',` when it should be `'#type' => 'contextual_links_placeholder',`. Sorry, not sorry. 😀

-mike

**Comment by andy-blum** [comment]
Looks like we're using the class's name cast to lowercase. We need to get the value of the .... annotation? idk what php calls that.

[Drupal's code](https://git.drupalcode.org/project/drupal/-/blob/11.x/core/lib/Drupal/Core/Entity/Element/EntityAutocomplete.php#L67-68):
```php
#[FormElement('entity_autocomplete')]
class EntityAutocomplete extends Textfield {
  // ...
}
```

[Our scraper](https://github.com/andy-blum/drupal-smart-snippets/blob/main/src/getRawElements.js#L45):
```js
const name = classElement ? classElement.name.name.toLowerCase(): undefined;
```

Hopefully `php-parser` is able to get the string we need.
