### ISSUE TITLE
Should this be used instead of Drupal 8 Snippets plugin

### ISSUE THREAD

**Issue by Benjen** [andy-blum/drupal-smart-snippets#3]
Hi There, It is mentioned that this is envisaged as a replacement for Drupal 8 Snippets plugin. Does this hold true for the current release? At this stage do you recommend using this instead of Drupal 8 Snippets or should this be used together with Drupal 8 Snippets?

**Comment by andy-blum** [comment]
I believe it should successfully replace Drupal 8 snippets. If you notice any problems or snippets that are missing, please let me know!

**Comment by andy-blum** [comment]
Following your question last night, I went and ran a quick search through the two snippets files. This extension adds the following hooks that the Drupal 8 snippets does NOT have:

```
hook_aggregator_fetcher_info_alter
hook_aggregator_parser_info_alter
hook_aggregator_processor_info_alter
hook_element_plugin_alter
hook_entity_preload
hook_entity_revision_create
hook_ENTITY_TYPE_revision_create
hook_field_info_alter
hook_help_topics_info_alter
hook_jsonapi_entity_field_filter_access
hook_jsonapi_entity_filter_access
hook_jsonapi_ENTITY_TYPE_filter_access
hook_oembed_resource_url_alter
hook_plugin_filter_TYPE_alter
hook_plugin_filter_TYPE__CONSUMER_alter
hook_removed_post_updates
hook_token_info
hook_token_info_alter
hook_views_plugins_filter_alter
hook_views_ui_display_tab_alter
hook_views_ui_display_top_alter
```

This extension is missing a single hook from Drupal 8 Snippets:
```
hook_node_access
```

I'm not sure why, but hook_node_access isn't listed in the 8.9.x node api, so my scraper didn't pick it up.
